server:
  port: 8111
spring:
  application:
    name: auth
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://127.0.0.1:3306/lbls?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 解决依赖循环问题
  main:
    allow-circular-references: true

  # redis 相关配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0